sudo: false

language: node_js
node_js:
  - "node"

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
    - openjdk-8-jdk
    - lib32stdc++6
    - lib32z1
env:
  CXX=g++-4.8

install:
  - npm install -g cordova
  - npm install -g monaca
  - npm install
  - cd ~/.cordova
  - npm install webpack babel-core babel-loader babel-preset-env babel-preset-es2015 babel-preset-react babel-preset-stage-2 babel-plugin-flow-runtime babel-polyfill html-webpack-plugin
  - cd ~/build/raven920/Lexico

before_script:
  - mkdir android-sdk-linux && cd android-sdk-linux && wget http://dl.google.com/android/repository/tools_r25.2.3-linux.zip && unzip tools_r25.2.3-linux.zip && cd ..
  - echo y | ./android-sdk-linux/tools/android update sdk --no-ui --all --filter tools
  - echo y | ./android-sdk-linux/tools/android update sdk --no-ui --all --filter platform-tools
  - echo y | ./android-sdk-linux/tools/android update sdk --no-ui --all --filter build-tools-25.0.2
  - echo y | ./android-sdk-linux/tools/android update sdk --no-ui --all --filter android-23
  - echo y | ./android-sdk-linux/tools/android update sdk --no-ui --all --filter extra-android-support
  - echo y | ./android-sdk-linux/tools/android update sdk --no-ui --all --filter extra-android-m2repository
  - echo y | ./android-sdk-linux/tools/android update sdk --no-ui --all --filter extra-google-m2repository
  - export ANDROID_HOME=$PWD/android-sdk-linux
  - export PATH=${PATH}:$ANDROID_HOME/tools:$ANDROID_HOME/platform-tools:$ANDROID_HOME/build-tools/25.0.2

  - cordova platform add android
  - monaca plugin add cordova-plugin-file
  - cd ./parche
  - git clone https://github.com/attaboy/react-codemirror.git
  - cd react-codemirror
  - git checkout set_options_only_if_changed
  - rm -rf .git
  - cd ../..
  - rm -rf node_modules/react-codemirror
  - mv parche/react-codemirror node_modules/
  - cp -rf parche/node_modules/* node_modules/


script:
  - monaca transpile
  - monaca build android
